typography_spectrum: 0.64447
color:
  brandColors:
    - '#1f0010'
    - '#f7edca'
    - '#b8d1bb'
    - '#c67e65'
    - '#c0542e'
  brandStrength: 0.875
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Rick Stevens Entertainment
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Rick Stevens Entertainment
purpose: []
