name: Rick Stevens Entertainment
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64447
title: Rick Stevens Entertainment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f0010'
    - '#f7edca'
    - '#b8d1bb'
    - '#c67e65'
    - '#c0542e'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
