layout_spectrum: 0.8003851736430079
typography_spectrum: 0.1207760947290808
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.7630876426119357
  lightness: 0.30761182541027665
  saturation: 0.2727070380933583
  rhythmicContrast: 0.9571987604722381
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Rick Stevens Entertainment
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Rick Stevens Entertainment
purpose: []
