name: Rick Stevens Entertainment
favicon: null
layout_spectrum: 0.49935
typography_spectrum: 0.68445
title: Rick Stevens Entertainment
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f0010'
    - '#f7edca'
    - '#b8d1bb'
    - '#c67e65'
    - '#c0542e'
  brandStrength: 0.3125
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
